name=CasioLink
version=1.0.0
author=Gustavo Ramirez
maintainer=Gustavo Ramirez
sentence=Comunicación entre ESP32-S3 y calculadoras Casio mediante Send() y Receive().
paragraph=Implementa intercambio de variables reales de 12 bits entre una Casio fx-9750GIII y una ESP32-S3.
category=Communication
architectures=esp32
includes=CasioLink.h
